---

setup:

    status:
        sleeptime: 0.1
        args: ~
    
    pulser_setup:
        sleeptime: 0.1
        args: 
            - 20000
            - 0.3
    dac:
        sleeptime: 0.1
        args: 
            - 1 
            - 2000
    fpgaload: 
        sleeptime: 0.1
        args: ~
    
    adcconfig:
        sleeptime: 0.1
        args: ~
        
    fpgaload:
        sleeptime: 0.1
        args: ~
        
    flush_events:
        sleeptime: 0.1
        args: ~
        
    fpgatrig:
        sleeptime: 0.1
        args: 
            - 0

    fpgatrig:
        sleeptime: 0.1
        args: 
            - 1
        
    pulser_start:
        sleeptime: 0.1
        args: 100        
        
# Looped arguments; not implemented. 
run: ~
    